version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container-udemy
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ${PATH_LOCAL_VOLUME}:/var/lib/mysql
